### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by Rudyvantuyn** [kallydev/pancakeswap-prediction-bot#1]
./build/pancakeswap-prediction-bot_linux_amd64 will not exist after download. 
Only: pancakeswap-prediction-bot will be in that directory and it won't recognise --help or ./build/pancakeswap-prediction-bot_linux_amd64 --private-key replace_me_as_your_private_key --amount 0.01.
Can you look into that?

**Comment by kallydev** [comment]
@Rudyvantuyn Hi, thanks for pointing this problem out to me, I just fixed the wrong build steps in README.md.

```diff
  # Ubuntu or Debian
- sudo update
- sudo apt install git make snapd -y
+ sudo apt update
+ sudo apt install git make snapd upx -y
  sudo snap install go --classic

  git clone https://github.com/kallydev/pancakeswap-prediction-bot
+ cd pancakeswap-prediction-bot
  make build && ls ./build
```
